frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/**'
          - 'frontend/public/**'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'

diagrams:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.puml'
          - 'docs/assets/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/actions/**'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose.yml'
          - 'Dockerfile'
          - 'frontend/Dockerfile'
          - 'webservice/Dockerfile'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/src/test/**'
          - 'frontend/**/tests/**'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/src/main/resources/**'

feature:
  - head-branch: ['^feat', '^feature', '^feat/']

bug:
  - head-branch: ['^bug', '^fix', '^hotfix']

assets:
  - changed-files:
      - any-glob-to-any-file: 'docs/assets/**'
