frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/**'
          - 'frontend/public/**'

nextjs:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/next.config.*'
          - 'frontend/src/**'

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/**/*.ts'
          - 'frontend/**/*.tsx'
          - 'frontend/tsconfig.json'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/**'
          - 'build.gradle'
          - 'gradle/**'
          - 'gradlew'
          - 'gradlew.bat'

spring:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/src/main/java/**/com/**/webservice/**'
          - 'webservice/src/main/java/**/com/**/envisionad/**'

java:
  - changed-files:
      - any-glob-to-any-file: 'webservice/src/**/*.java'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'
          - 'pull_request_template.md'

diagrams:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.puml'
          - 'docs/assets/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/actions/**'

infra:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/labeler.yml'
          - '.github/*.yml'
          - '.github/*.yaml'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose.yml'
          - 'Dockerfile'
          - 'frontend/Dockerfile'
          - 'webservice/Dockerfile'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/src/test/**'
          - 'frontend/**/__tests__/**'
          - '**/*_test.*'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - '.env*'
          - 'webservice/src/main/resources/**'
          - 'frontend/.env*'
          - '**/*.properties'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'webservice/src/main/java/**/security/**'
          - 'webservice/src/main/java/**/configuration/security/**'

feature:
  - head-branch: ['^feat', '^feature', 'feat/.*']

bug:
  - head-branch: ['^bug', '^fix', '^hotfix']

chore:
  - changed-files:
      - any-glob-to-any-file:
          - '.idea/**'
          - '**/*.iml'

assets:
  - changed-files:
      - any-glob-to-any-file: 'docs/assets/**'
