@startuml
!include <archimate/Archimate>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/postgresql.puml

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/devicons2/nextjs.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!include SPRITESURL/auth0-icon.puml
!include SPRITESURL/cloudinary-icon.puml
!include SPRITESURL/stripe.puml
!include SPRITESURL/google-gmail.puml

AddElementTag("service", $shape=EightSidedShape(), $bgColor="Green", $fontColor="white", $legendText="API \neight sided")
AddElementTag("ext_service", $shape=EightSidedShape(), $bgColor="Gray", $fontColor="white" ,$legendText="External Services\neight sided")
AddElementTag("PostgreSQL Database", $shape=RoundedBoxShape(), $bgColor="#336791",$borderColor="Black", $fontColor="white", $legendText="Database")
AddElementTag("nextjs-app", $shape=RoundedBoxShape(), $bgColor="#000000", $fontColor="white", $legendText="Next.js Application")

SetDefaultLegendEntries("")

allowmixing

rectangle "Developer's Laptop \n[Deployment Node: Windows 11 and Linux Fedora 39]" as laptop {

    node "Docker Container - API \n[Deployment Node : Docker]" as backend {
        node "Apache Tomcat\n[Deployment Node : Apache Tomcat/10.1.13]" as tom {
            Container(java, "Java Spring Boot", "Container: Java and Spring Boot","Provides a platform where media owners list ad spaces and advertisers book and manage campaigns.", $sprite="java", $tags="service")
        }
    }

    node "Docker Container - Database \n[Deployment Node : Docker]" as db {
        node "PostgreSQL Server \n[Deployment Node : PostgreSQL/16.x]" as sql{
            Container(postgres, "PostgreSQL Database", "Container: PostgreSQL Schema.","Stores all the data of the organization related to media, advertising, reservations, and payments", $sprite="postgresql", $tags="PostgreSQL Database")
        }
    }

    node "Web Browser \n[Deployment Node : Chrome and Firefox]" as browser {
        node "Next.js Development Server \n[Deployment Node : Next.js Dev Server]" as nextjs_node {
            Container(nextjs, "Next.js Application", "Container: TypeScript, Next.js, React","Provides all the Envision Ad functionality to clients via their web browser. Handles server-side rendering and static generation.", $sprite="nextjs", $tags="nextjs-app")
        }
    }

}

Container_Ext(cloudinary, "Cloudinary Service", "REST API", "Cloudinary's image hosting service and API.", $sprite="cloudinary-icon", $tags="ext_service")
Container_Ext(auth, "Auth0", "SaaS", "Auth0 is an easy to implement, adaptable authentication and authorization platform.", $sprite="auth0-icon", $tags="ext_service")
Container_Ext(email, "Gmail SMTP System", "Email Service", "The google SMTP emailing system.", $sprite="google-gmail", $tags="ext_service")
Container_Ext(stripe, "Stripe", "Payment Service", "Payment processing service for handling reservations between advertisers and media owners.", $sprite="stripe", $tags="ext_service")

nextjs -[dashed]-> auth : Authenticates users via\n[OAuth2/HTTPS]
nextjs -[dashed]-> java : Makes API calls to \n[JSON/HTTPS]
java -[dashed]> postgres : SQL/TCP\n[JDBC]

java -[dashed]-> cloudinary : Makes API calls to \n[JSON/HTTPS]
java -[dashed]-> stripe : Makes API calls to \n[JSON/HTTPS]
java -[dashed]-> email : Sends email to \n[SMTP/TCP/IP]
SHOW_LEGEND()
@endpuml