@startuml
!include <archimate/Archimate>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/postgresql.puml

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/devicons2/nextjs.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!include SPRITESURL/cloudinary-icon.puml
!include SPRITESURL/stripe.puml
!include SPRITESURL/google-gmail.puml

SetDefaultLegendEntries("")

AddElementTag("java", $shape=EightSidedShape(), $bgColor="Green", $fontColor="white", $legendText="Java File \neight sided")
AddElementTag("ext_service", $shape=EightSidedShape(), $bgColor="Gray", $fontColor="white" ,$legendText="External Services\neight sided")
AddElementTag("typescript", $shape=RoundedBoxShape(), $bgColor="DodgerBlue", $fontColor="white", $legendText="TSX File")
AddElementTag("html", $shape=RoundedBoxShape(), $bgColor="OrangeRed", $fontColor="white", $legendText="HTML Files")
AddElementTag("npm_libraries", $shape=EightSidedShape(), $bgColor="Red", $fontColor="white" ,$legendText="NPM Libraries\neight sided")
AddElementTag("TSX_component", $shape=EightSidedShape(), $bgColor="Blue", $fontColor="white" ,$legendText="TSX Component\neight sided")
AddElementTag("framework-nextjs", $shape=RoundedBoxShape(), $bgColor="#000000", $fontColor="white", $legendText="Next.js Application")

Container_Ext(email, "Gmail SMTP", "SMTP Service", "The google SMTP emailing system.", $sprite="google-gmail", $tags="ext_service")
Container_Ext(cloud, "Cloudinary", "Cloud Service", "Cloud storage service that stores media and pdf reports.", $sprite="cloudinary-icon", $tags="ext_service")
Container_Ext(stripe, "Stripe", "Payment Service", "Payment processing service for handling reservations between advertisers and media owners.", $sprite="stripe", $tags="ext_service")

        rectangle "API" as API #line.dashed{

                Container(securityFilter, "Security Filter", "Component: Spring Security Filter", "Filters all the requests to the API.", $sprite="java", $tags="java")

                package "Media"{
                    Container(MediaController, "Media Controller", "Component: Spring Boot Rest Controller", "Allows Media Owners to manage MediaAssets, Admins to manage both MediaAssets and MediaTypes, and Advertisers to view MediaAssets.", $sprite="java", $tags="java")
                    Container(MediaService, "Media Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(MediaRepo, "Media Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    MediaController -[#LimeGreen]-> MediaService  : **Uses**
                    MediaService -[#LimeGreen]-> MediaRepo  : **Uses**
                }

                package "Advertising" {
                    Container(advertisingController, "Advertising Controller", "Component: Spring Boot Rest Controller", "Allows Advertisers and Admins to manage Advertisements and Advertisement Campaigns.", $sprite="java", $tags="java")
                    Container(advertisingService, "Advertising Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(advertisingRepo, "Advertising Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    advertisingController -[#LimeGreen]-> advertisingService  : **Uses**
                    advertisingService -[#LimeGreen]-> advertisingRepo  : **Uses**
                }

                package "Reservation" {
                    Container(reservationController, "Reservation Controller", "Component: Spring Boot Rest Controller", "Allows Media Owners and Advertisers to view Invoices and Reservations, and Admins to manage them.", $sprite="java", $tags="java")
                    Container(reservationService, "Reservation Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(reservationRepo, "Reservation Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    reservationController -[#LimeGreen]-> reservationService  : **Uses**
                    reservationService -[#LimeGreen]-> reservationRepo  : **Uses**
                }

                package "Email"{
                    Container(mailerService,"Mailer Service", "Component: Spring Boot Service", "Sends emails to the users.", $sprite="java", $tags="java")
                }

                package "Organization"{
                    Container(organizationController, "Organization Controller", "Component: Spring Boot Rest Controller", "Allows all users to manage their account", $sprite="java", $tags="java")
                    Container(organizationService, "Organization Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(organizationRepo, "Organization Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    organizationController -[#LimeGreen]-> organizationService  : **Uses**
                    organizationService -[#LimeGreen]-> organizationRepo  : **Uses**
                }

                package "Payment"{
                    Container(paymentService,"Payment Service", "Component: Spring Boot Service", "Handles payment for the users.", $sprite="java", $tags="java")
                }

                package "File"{
                    Container(fileService,"File Service", "Component: Spring Boot Service", "Handles files for the users.", $sprite="java", $tags="java")
                }

                organizationService -[dashed]-> mailerService  : **Sends Email using**
                advertisingService -[dashed]-> mailerService  : **Sends Email using**

                fileService --> cloud  : **Upload Files Using**\n[HTTPS/API]
                mailerService -[dashed]-> email  : **Send Email Using**\n[SMTP/TCP/IP]
                paymentService --> stripe  : **Process Payments Using**\n[HTTPS/API]

                advertisingService --> fileService  : **Get Files using**
                MediaService --> fileService  : **Send Files using**

                reservationService --> paymentService  : **Process Payment using**

                securityFilter -[#RoyalBlue]-> advertisingController  : **Direct Request**
                securityFilter -[#RoyalBlue]-> MediaController  : **Direct Request**
                securityFilter -[#RoyalBlue]-> reservationController  : **Direct Request**
                securityFilter -[#RoyalBlue]-> organizationController  : **Direct Request**

            SHOW_LEGEND()
        }

        ContainerDb(db, "Database", "Database: PostgreSQL", "Stores all the data for the system.", $sprite="postgresql", $tags="database")

        advertisingRepo -[#LimeGreen]-> db  : **SQL/TCP**\n[JDBC]
        MediaRepo -[#LimeGreen]-> db  : **SQL/TCP**\n[JDBC]
        reservationRepo -[#LimeGreen]-> db  : **SQL/TCP**\n[JDBC]
        organizationRepo -[#LimeGreen]-> db  : **SQL/TCP**\n[JDBC]

Container(nextjs_app, "Next.js Application", "TypeScript, Next.js, React", "Provides all the Envision Ad functionality to clients via their web browser. Handles server-side rendering and static generation.", $sprite="nextjs", $tags = "framework-nextjs")

nextjs_app --> securityFilter  : **Makes API calls**\n[HTTPS/JSON]

@enduml