@startuml
left to right direction

' --- Increase spacing and make the box larger test ---
skinparam ranksep 40
skinparam nodesep 30
skinparam rectangle {
  Padding 40
  Margin 40
}

actor Advertiser as ADV
actor "Media Owner" as MO

rectangle "Publish Ad" {
' --- Advertiser use cases ---
  usecase "UC_13.3 Preview Ad on Media" as Preview
  usecase "UC_13 Submit Ad for Approval" as Submit
  usecase "UC_07 Confirm Proof of Display" as ConfirmProof
  usecase "UC_03 Make Ad Payment" as Pay
  usecase "UC_13.2 Upload Ad Content" as UploadContent
  usecase "UC_13.1 Select Ad Start/End Dates" as SelectDates

  ' --- Media Owner use cases ---
  usecase "UC_04 Approve/Deny Ad" as ApproveAd
  usecase "UC_14.1 Download Ad Content" as DownloadContent
  usecase "UC_06 Provide Proof of Display" as ProvideProof
  usecase "UC_14 Retrieve Ad for Display" as DisplayAd

  ' --- Actor connections ---
  ADV -- Submit
  ADV -- ConfirmProof

  DisplayAd -- MO
  ProvideProof  -- MO

  ' --- Relationships  ---
  Submit <.. Preview : <<extends>>
  Submit ..> SelectDates : <<includes>>
  Submit ..> UploadContent : <<includes>>
  Submit ..> Pay : <<includes>>
  ConfirmProof ..> ProvideProof  : <<includes>>
  DownloadContent <.. DisplayAd : <<includes>>
  ApproveAd <.. DisplayAd : <<includes>>

}
@enduml