@startuml

' --- Increase spacing and make the box larger ---
left to right direction
'skinparam linetype ortho

skinparam rectangle {
  Padding 40
  Margin 40
}

actor Advertiser as ADV
actor "Media Owner" as MO
actor Admin as ADM
actor "Guest User" as GU

' --- Hourglass actor for temporal use cases ---
hide stereotypes
rectangle "<img:https://cdn-icons-png.flaticon.com/512/3889/3889548.png{scale=0.12}>" as HG <<Temporal>>
skinparam rectangle<<Temporal>> {
  BorderColor white
  BackgroundColor white
}


rectangle "Envision Ad" {
  ' --- Advertiser use cases ---
  usecase "UC-03 Make Ad Payment" as Pay
  usecase " View Media Details" as ViewMediaDetails
  usecase "UC_01 Browse Media Inventory" as Browse
  usecase "UC_06 Provide Proof of Display" as ProvideProof
  usecase "UC_13 Create Pending Reservation" as CreatePendingReservation

  ' --- Media Owner use cases ---
  usecase "UC_09 Manage Media Listing" as ManageListing
  usecase "UC_12 View Ad Requests/History" as ViewAd
  usecase "UC_15 Notify Advertiser of Approval Decision" as NotifyApproval
  usecase "UC_16 Remind Media Owner to Update Media Content" as StartAd
  usecase "UC_17 Remind Media Owner to Send Proof of Display" as SendProofReminder
  usecase "Manage Reservation" as ManageReservation

  ' --- Admin use cases ---
  usecase "UC_08 Approve/Deny Media Listing" as ApproveListing
  usecase "UC_10 Issue Content Warning" as ContentWarning


'  ' --- Note ---
'  note right of ConfirmProof
'  <b>Precondition</b>
'  Proof of display must be first
'  provided by the Media Owner
'  end note
'
  ' --- Actor connections (solid lines) ---
'  ADV -- Browse
  ADV -- Browse
  ADV -- CreatePendingReservation
'  ADV -- ConfirmProof

  ' keep media owner lines inside rectangle
'  MO -[hidden]-> ApproveAd
'  MO -[hidden]-> Proof
'  MO -- ApproveAd
  MO -- Browse
  MO -- ViewAd
  MO -- ManageListing
  MO -- ProvideProof

  ADM -- ApproveListing
  ADM -- ContentWarning

  HG -- SendProofReminder
  HG -- StartAd
  HG -- NotifyApproval

  GU -- Browse
  ' --- Relationships (dotted, no arrows, all contained) ---
  ViewMediaDetails -> Browse : <<extends>>
  Pay ..> ManageReservation : <<includes>>
  ManageReservation ..> CreatePendingReservation : <<includes>>
'  Request <-- ApproveAd     : <<extends>>
'  ConfirmProof <-- Proof   : <<includes>>
'  ApproveAd <-- Proof      : <<includes>>
'  ManageListing <-- PublishAdOnMedia : <<extends>>
}
@enduml