sprite $doppler [511x512/16z] {
xDt7cUDG30JXCwhvYVbdkvTruqMpvW5LAVniZ9Mq7yn8NhRjCx974dwKa1_jxRE45uKaKvu0XmylIyYq1y3bl-IV-G283uIa-mDWZ_1-2Hds03Zzb_oz_Iry
NCXOV_K9S_tL9o5J_TM7aB7-wXFc-gjFGgRwgmyXO_tL9_JqDvufcSll-25ahB_wX8R-nfCbS_aTFuHCz7VyNd_7JuREt_5x_TKdP9Q_jz_hx_hbT_nUV_bf
n6_WzPVV7_sy_LUlFtk_vFVwo-_rzqk__FA7aVpUVldbPoo_jz__zvO_W_dbPoo_N_hbbp-CvFVsooy_BVZjSPgVaVn-wVTjVkHdBhzV-kMNdudytdxVuTNn
W_nlgf9_NaMzZ1h07-B7F8Nw8ERnQ_zxfErtVi1qVgYlWc7yuhyC6jv-FzgfdYyz-PdBNyUIl-5FUiiVW5pbPw8-rE5eCdu_rXFgHFJZPo9_5NMgZlppzC_N
a9zX_D37dwibm_YfHlxXQc6KVbtJBnPUl_nrlMxyJEEdhaGl_k3u5zr_kFFwgx_O_hcJVvF_oTAA7yT_i4xy6S9FDVD_SEFrtnp_OlxSKd3ynvD_hUhcsl27
9CX_B9hm4np_WllVE97yNVovaH_vJzI3FqJzCz617_dFjZNWz_QlUFutxihV-Ipepst5st--1lp8Vxxr-NVvBpIQN_uQVVlbhz7Zbxz6yyjV2_CZ_-LObt-N
VxdvXxkA_7Sq-lRBNwDll_or97_alwlHwvU_HklBNwDll_mrUltoinP_TlblZT7y-jSY-lBBlyj_U_Bhlm2__6lwF_wvllpVsB5ptCXXA02YQJslzp_jh0o4
8KQmYPPXk_cYdvV4BIU--S-_-zVfj_3Dyk_y0Ha2GTG7zj_rt-_HROGgpdsI_FlIFsHHn76iG832KLVsVzhvLrYKeQ9KHOgY37Nzy-y3U-rVpPztAr0fgYh7
YVpha-JVF_yW3EMjAgXAgah72J5asFa_bHAGYawN-vhgLvednEoo_FRQlq0Xgl8_KtQe1at4qDNz7y7--HS87PpaLs4kNVF841VtVx3OV-T_R3P5IwWgS-aq
WpBx5FdtsZyqGnKCbGPLEgLIb8F0LVdTwEVV_Jl9tw1pL081WOTFdd_thmA2L5e4286dQ-gxuTg_-wCg8FHsAYebA0IvA3-tox_xfw1AqWg2L4dXS-JVQ_zG
dKDh52fK8zFdo_zwPlVl9tjtkjsuZWDnV3PBBD1jlF_JpfPSdFXaio0k85J_MR__Rj6KuavxipT4fjzu_lWGn-yBBqcw-EqjO06inkEtoE-hbau1zl-iqeqV
FFkTbSuz_xWm5dzLLlhs_3RvOkkdF-porzB_0JmNLf_-_winlwp2J_yd_df1VlhR2s1quaTiVPx_JKz_V2ugF_rXBm8QyKjZVeQk-FP_W5xyEAFFQkbUPtwS
uMTZ_9i_zLlX-UaFj1-_5LwV_e7v6PRWnwhyV00iqdxyLdnzlW2CpC_YywCZFqDmVi7tdTTdVwxDpqhFz6Hem5zrJlJlENwq6JzRb1-n-UaFFHb6yBEW_CZA
Vw__JwEq93yMrAzVfFEBpk_tZqnlfVGNFPLaug-_fNEJoEFt-p_2sriwjHgCNvhmhs1lwTIMuZT_HEQl1zEPhNFsMv7NNptfn8AEtyzVWzhdzqUxyVlzOz77
zuy-_lZyrLhHVmyuVh__KlRMG-SLSFn-_t3syG-0SEFtymUqZx__6cpyVl_bx2sTMQ1d_lZyrQ9_4twimryj-dSQlzz_W3tzU-Z7vw-zkw_f3ntDZz7wTKWw
jLdw4fp_Nh-D_kWm_a3yTMGB_X507Jb-I-3bzzldzw_ZzHMk-g-_JaXd5qpVpz_VdluwZHyT-UkyT7uZyHL-VdJHb_f2z8TeWoGOVvsTHcZl_BHlmL-7ix_E
xw4XmWXyHIZ-6Y6DaiD-93y4BVaDd_oM_xhdr_SV08troM_TeUqJjFNFe5z5hnBYhB_6YVgZ-UzrTEINCFoF6YcEVp1_3HNrNquW42k5VgM-xm2e2VJ9xzMN
PVJ9ZrQHFvU-tp-7VgM-pp-1Fld9JtsN_nBwv4Vh11VcfxxnXzSdVxqoF_bH2bf7_dNqs_FBctzuVV83fOC_-PVHx-V_87_i2ifxFTOFFPP83PWatdu_VXm_
_Qjm_0EhXk_m9t-AI_z5-Sd_jFtc_Xx-uVxKjrgl7-IFhT_NNo07zIKWlwJLx-ilECel4VcfxqqEhr_8Fq7VGjiS_29rLjGlK_c5_FFqyNd-NFyry2sqhJhM
7ybVBgIF__ENwQU_2CS_OViec7pwYrK7H_tohb_IyfE__1G0k_w3_7APxPk_wS_Yj-hGk7qx_rFoKx-MrqB3VmPg47_gupLxEm6cpT-gWwE-bOgV-g-xl_zd
2l_ZcL-eFnR_-KEW2t_y-SkrzIsSpy4_s_z1_MONG5dENtE5uYu9F-zyVluobD_yhLdwdBwz04hAp-dtVm9Khxyrt9xu5eRFltxY5zexQeHV1lEhV6xmWnxn
dt_-KqRowpZ-k_uSyKz_0qWFzv0l6lrgZ_eMhF7pjyOVzyJ7-NU0ectyHu-U-1RWznUDug-gnFVok_t_DFAVSDmJtww0Rd_HDluyxdyEfLyOpQ_r1N_AMwLx
A6x-yGV0NPNuRGD2-NFqXf-BtphihvUhbZAIlpJWzxy1v77_N1cOz_s_w9bUuLUB-5rpdlxz_W5GfVt8Hl9RN_bBLTeF3cNu_AqFt__GAxSNwnhpjrYP7Cea
VYObGZFyMIdx7a-_Fp-JlUnl5Mkfur-TiLBUsCt_8lDdUzcjyjV_N82VxLzNflEZhp_3r_3cVwcxFqTlbJV--VvmtFuUwehop_plyz-dVmICcp_bpT_S9-EF
vAUyLMA4Wg7-bBS7lo2v-HcstLc85xzm-xDjTzW7U_WdlqlUSilRv_zA_FJVdjhT_k_wE_bNQTy-j_ipUVf7R_k-3Fv08VyBcy_fZu92_qzXUo4dVApzurcV
_BVjbNQlVod1tlrm_choPl-2_-xajxi_-SEqtKp-vNpyKVnv_9ly_zeSkUTV0it_olot3tduDz_bhyptvwlV_KtztTxXl-w37_blrb_-X_MtVVFxyyr_07ph
W7wEDx_-snzqyVvs-wg1_6MVDd_U_hwKTnm0kxNEwK__hvTlyn_6p_bFQFjiRmy01_6tRUFyr-fV1kxmRxZ_9VKjIQR_JZ_Y-cVy2_jB7dtBON_2Fmu_hZB_
xVOB_sqGVx5t_o7uFVvvjcyTvj-DttFps_T0wy_FRypjvf_Zy7VvvzDtTCf_vSi_9D7HRsV_o4V_WVhalxK_-xSzpRCV7FvfzCr_9FyUxBrlPlz_lO3l-R7l
diJVypSzYAGQl_7tl_oRVnZzSfmVacVy_c_yfVdpNYMj_wlsjvk7VqlWR_m9_SljvRQH_YNGzHzvht-lqdluztDFVs7yuVANceFV_pFVy_mxvz-pFaU_wIVu
se_nP_Htu8yy_SlI_93Sw-_llvSW8UN-NzVt7V_xIVqO_d1__Clo-kRlch_txS_YVzpJ-2K1lnt_TWPSxqk_Nlvx4dxVwP-57oW-VdcaMR_FV_UtylhD_vhh
j_puwn_-vdzL_ZpV-a7nhLya4t-Gkvz-LT3vIrJ-yFxFyz_rrMeK_xVMvzyQ7Fx-wv_wckulxoNWF-c_kV1Dtjzz_lf54l0Ftx-sQpn_VF_Rk0__RHwzDTV_
iVfd_-qsw3iVHRirZr_k2_DRtT_zQU-6V_fR6YkNVbT_7HDy_Cdy3zlx-VSjXhs5OT_v2Ui_xEp_Ns7ihJ7x5mZI-6--Vbx_fhCwPEzyx_zy0Ynz-lVWrwdv
nk_dbukjtxxpxTjz_sfNVGWS_fdkVhjzwI-OlUNXzz__wiNyl-JNK64WlzGhtVsDtzfsZTS8Vkjg_1-thq7hw2zf_4_-r4SZXzzU-nIlVb3_spZ_RTyqV7tM
Bsdy_QU_MckU02Z8v_-l8VoxBbIxN_HWILZ_0VowM7_GzUfdrGlmwue13VZfhyk6hlnMtg_xxxfqWWw7VqJ_lOU_hb_F1p-h9lo-loO9hVWJ-5lvxQs23lpH
_Vs_tlMcoVg3VbS_AvI__ni_cZ6WcxxrMFxNkzuqQmMctujVwjA_us_Nr04T-AFvE_blDqrVGPFd_XmNW0_qswQN2EWzVwch_FZFPh_fTG8Aqllhg_wtswxN
2kUIDVpr9_Rt_oIsfxy-at_-_t_Jez5V82zK7ngXxVdNEbX-U-x_DV-gCTe_VCvRUlMwwLjLu_ItPlBq5uS_et-Aw2zNzgU_zF9dz6SV_-QbrVqVoavzBHib
chySyRyhE_l7Cl4dah_nztu1H7mBSVm5CioV-9RsIE18nlaJtqBw_VE-5zzVZlAVzEVqBSJOlqWJVrRBmMBi_oY_umK0fnzc_tv-yx-h8-h7yFVpctzLHzIF
wE_YV_PdAClworb_9gN4yQyZ-AjQh9H8_dBK7mv-fp_r-_iF-F0tVrQYyMlNDt_MGrLPBIlx6xx3_wxAIWdeBrrFVqkf7v9V-rxzBF8tQAw_Xz-YVipvwu33
d_vbUNy_F_qHc5_wFFfLY_wbKHFdR_Xk_mVv8ypVl_-J_dVg1-1t-uiuZt-B_0lxIqv_yclp-TFVAg7u_Vvoj1hEd_n-Vy5KV_8NdUSl9n_-BEf7dByuZlyq
_kHNl59MV_AhaBzz2CRlznSU_yShw_1hnq__-FxaLsdBp_cNUFn-Vu5azYU__gplub_7d_mgd7-xa8fVhDFyTuu_9BywhdwBpP_y_lsZaJ_F_kE9ZcZCyQ-E
EFwv_f9__kHNQR1-Vl6dzkEFxy_vbw3yVd-vnFp9hp_p8oK_F_gjk_IUF_K3ywkRF_wV-YA_tn-Nc3_vzO2-ov_wXr9hulwZyfC_lZ_v_K6d-mkauUsF-j7v
LLBoazz__ei_yljJQ-hh7xa0FyTlrMx-6Z_oAnhooshyvDVv_DGlejEITlpYvUVuO_ZBkPpwvC_cJtq7_tH_EUjFVayQnby4r-3dsM_TfVNyDMt8nwyYfdys
ZdyzViLV_eBhyPDVHLeU_vgslH5vC7vjTlmxz7dl3-8lW9oD_8U2nl5_ruUSABC-ylAhG02G_uTALdxplwe--Qi8Vg0dVqsfRpduEVuy_0gvC3_vLSRfan_X
-DLnywE-CvX-altVTSruzbk2YEFdsH_VNuz4_PZysbsV_0ZChztrkNu0ff_1lrB_C3-WCUjzvoV_Mvh3Nmz6_cByCQF-KtlxzPV8_DeLd-zyRFnXw_UfJtuO
V-28RsT_u-piZrszzB5lTT67hb3jOqz-NIS7FVMTBtton_6J_p_jtCLX144KnD3hbwdpZzPi7vTPgeK4tjHGWtkeF_xuDUcnB_tA3z__KlxuV_xS_Btn5VF7
Fy3hCYP-cChVJ9_IfL-N7li1cALC_53vuo_T-ScIFsB--37onvz-_63aZp_--07pZN_y__WyBrlo7xJbZv-1GSmVFrx-tlfxzQi_02FcZty6wLX_M_dZ7Uwf
_ip8-Rlvi-jtzJVonuzPFty6c47Adp_QEPxnqnJVxlx4-lbpv_g5e_MVbZ3L7-_B_bx-jQQ_ox-w-_dRkfz_-bt_qw__pedz7G1LFt-bVWT0-Dq1hiTCUPhj
UUHRlc9lVh5VyWkdEEUN3m
}