@startuml
title Publish Ad

actor "Advertiser" as Advertiser
participant "__:System__" as System

Advertiser -> System: getMedia()
System --> Advertiser: MediaDetails

Advertiser -> System: reserveMedia()
System --> Advertiser: ReservationModal

Advertiser -> System: submitAd(mediaId, adImage, startDate, endDate)
System --> Advertiser: AdPreviewOnMedia

Advertiser -> System: goToPayment()
System --> Advertiser: PaymentScreen

Advertiser -> System: confirmReservation(paymentDetails)
System --> Advertiser: closeModalAndShowConfirmation

@enduml
